### ISSUE TITLE
"artist_urlL" should be "artist_urlL:" at https://github.com/RustyRin/bandcamp-api/wiki/Functions

### ISSUE THREAD

**Issue by matkoniecz** [RustyRin/bandcamp-api#4]
https://github.com/RustyRin/bandcamp-api/wiki/Functions

![screen01](https://github.com/RustyRin/bandcamp-api/assets/899988/20743ab9-65c2-4e8b-bcf9-e58b8530b2f1)

**Comment by RustyRin** [comment]
done
